"""add chat and tableau models

Revision ID: 7cd98763c15e
Revises: 
Create Date: 2026-02-01 18:40:00.246750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd98763c15e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('datasources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tableau_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_datasource_project', 'datasources', ['project'], unique=False)
    op.create_index('idx_datasource_updated', 'datasources', ['updated_at'], unique=False)
    op.create_index(op.f('ix_datasources_id'), 'datasources', ['id'], unique=False)
    op.create_index(op.f('ix_datasources_tableau_id'), 'datasources', ['tableau_id'], unique=True)
    op.create_index(op.f('ix_datasources_updated_at'), 'datasources', ['updated_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_user_active', 'sessions', ['user_id', 'last_active'], unique=False)
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_last_active'), 'sessions', ['last_active'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tableau_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workbook', sa.String(length=255), nullable=True),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_view_datasource', 'views', ['datasource_id'], unique=False)
    op.create_index('idx_view_updated', 'views', ['updated_at'], unique=False)
    op.create_index('idx_view_workbook', 'views', ['workbook'], unique=False)
    op.create_index(op.f('ix_views_datasource_id'), 'views', ['datasource_id'], unique=False)
    op.create_index(op.f('ix_views_id'), 'views', ['id'], unique=False)
    op.create_index(op.f('ix_views_tableau_id'), 'views', ['tableau_id'], unique=True)
    op.create_index(op.f('ix_views_updated_at'), 'views', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_views_updated_at'), table_name='views')
    op.drop_index(op.f('ix_views_tableau_id'), table_name='views')
    op.drop_index(op.f('ix_views_id'), table_name='views')
    op.drop_index(op.f('ix_views_datasource_id'), table_name='views')
    op.drop_index('idx_view_workbook', table_name='views')
    op.drop_index('idx_view_updated', table_name='views')
    op.drop_index('idx_view_datasource', table_name='views')
    op.drop_table('views')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_message_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_last_active'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    op.drop_index('idx_session_user_active', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_datasources_updated_at'), table_name='datasources')
    op.drop_index(op.f('ix_datasources_tableau_id'), table_name='datasources')
    op.drop_index(op.f('ix_datasources_id'), table_name='datasources')
    op.drop_index('idx_datasource_updated', table_name='datasources')
    op.drop_index('idx_datasource_project', table_name='datasources')
    op.drop_table('datasources')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
